name: utopia_loadbalancer
description: A generic load balancer and multi-process scaling library for Dart applications
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dev_dependencies:
  test: ^1.21.0
  lints: ^3.0.0
